// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// model_landsepi
void model_landsepi(Rcpp::List timeP, Rcpp::List landscape, Rcpp::List dispersal, Rcpp::List inits, int val_seed, Rcpp::List hostP, Rcpp::List pathoP, Rcpp::List evolP);
RcppExport SEXP _landsepi_model_landsepi(SEXP timePSEXP, SEXP landscapeSEXP, SEXP dispersalSEXP, SEXP initsSEXP, SEXP val_seedSEXP, SEXP hostPSEXP, SEXP pathoPSEXP, SEXP evolPSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type timeP(timePSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type landscape(landscapeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type dispersal(dispersalSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type inits(initsSEXP);
    Rcpp::traits::input_parameter< int >::type val_seed(val_seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type hostP(hostPSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type pathoP(pathoPSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type evolP(evolPSEXP);
    model_landsepi(timeP, landscape, dispersal, inits, val_seed, hostP, pathoP, evolP);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_landsepi_model_landsepi", (DL_FUNC) &_landsepi_model_landsepi, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_landsepi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
